###############################
# Our Custom Web Dav Properties
###############################
## iCloud Web Dav Properties
web:
  dav:
    apple:
      calendarServer: https://caldav.icloud.com/
      cardServer: https://contacts.icloud.com/
      ftl:
        currentUserPrincipal: web/apple/CurrentUserPrincipal.ftl
        displayName: web/apple/DisplayName.ftl
    google:
      calendarServer: https://caldav.icloud.com/
      cardServer: https://contacts.icloud.com/
